- name: init cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: setup kubectl
  shell: |
    mkdir -p /home/ubuntu/.kube
    cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    chown -R ubuntu:ubuntu /home/ubuntu/.kube

- name: install fannel
  become_user: ubuntu
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_cmd

- name: save join command
  local_action: copy content="{{ join_cmd.stdout }}" dest=/tmp/k8s-join.sh